notify:
  # В чате отправляется сообщение с
  # зашифрованами координатами золото спавнера
  enable: false
  messages:
    - ""
    - " &eЗолотой спавнер &fбыл установлен"
    - " &fНа координатах &6%coordinates%"
    - ""
  settings:
    symbols: # Символы которые шифруют координаты
      - "#"
      - "*"
    coordinates:
      x: true # Отображать ли X координату
      y: true # Отображать ли Y координату
      z: true # Отображать ли Z координату

item:
  material: GOLDEN_PICKAXE
  name: 'Золотая кирка для Золотого Спавнера'
  lore:
    - ' Кирка которая может добыть спавнер'
  glow: false # свечение кирки?
  message-break: true # Будет ли сообщение при ломание спавнера?
messages:
  no-perm: 'Эээ hello модератор!'
  break-spawner: 'Спавнер выпал. Скорей его подберай!'